"""first migration

Revision ID: 0242ec941ee9
Revises: 032cb5be7d35
Create Date: 2025-10-10 20:32:00.704642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0242ec941ee9'
down_revision: Union[str, Sequence[str], None] = '032cb5be7d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_activity_table_destination_id_destination_table'), 'activity_table', type_='foreignkey')
    op.create_foreign_key(op.f('fk_activity_table_destination_id_destination_table'), 'activity_table', 'destination_table', ['destination_id'], ['destination_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_activity_table_destination_id_destination_table'), 'activity_table', type_='foreignkey')
    op.create_foreign_key(op.f('fk_activity_table_destination_id_destination_table'), 'activity_table', 'destination_table', ['destination_id'], ['destination_id'])
    # ### end Alembic commands ###
