"""first migration

Revision ID: 032cb5be7d35
Revises: 900c42f1c4ea
Create Date: 2025-10-10 20:29:58.019645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032cb5be7d35'
down_revision: Union[str, Sequence[str], None] = '900c42f1c4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_destination_table_trip_id_trip_table'), 'destination_table', type_='foreignkey')
    op.create_foreign_key(op.f('fk_destination_table_trip_id_trip_table'), 'destination_table', 'trip_table', ['trip_id'], ['trip_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_destination_table_trip_id_trip_table'), 'destination_table', type_='foreignkey')
    op.create_foreign_key(op.f('fk_destination_table_trip_id_trip_table'), 'destination_table', 'trip_table', ['trip_id'], ['trip_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
