"""first migration

Revision ID: 68eadfada9c8
Revises: 29fd9b654529
Create Date: 2025-10-12 13:54:40.089441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68eadfada9c8'
down_revision: Union[str, Sequence[str], None] = '29fd9b654529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_trip_association_course_user_id_user_table'), 'user_trip_association_course', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_trip_association_course_trip_id_trip_table'), 'user_trip_association_course', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_trip_association_course_trip_id_trip_table'), 'user_trip_association_course', 'trip_table', ['trip_id'], ['trip_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_user_trip_association_course_user_id_user_table'), 'user_trip_association_course', 'user_table', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_trip_association_course_user_id_user_table'), 'user_trip_association_course', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_trip_association_course_trip_id_trip_table'), 'user_trip_association_course', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_trip_association_course_trip_id_trip_table'), 'user_trip_association_course', 'trip_table', ['trip_id'], ['trip_id'])
    op.create_foreign_key(op.f('fk_user_trip_association_course_user_id_user_table'), 'user_trip_association_course', 'user_table', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
