"""first migration

Revision ID: 7449ea78d2cc
Revises: eb656e1803bd
Create Date: 2025-10-08 10:09:58.748170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7449ea78d2cc'
down_revision: Union[str, Sequence[str], None] = 'eb656e1803bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_activity_table_activity_id'), 'activity_table', ['activity_id'])
    op.create_unique_constraint(op.f('uq_destination_table_destination_id'), 'destination_table', ['destination_id'])
    op.create_unique_constraint(op.f('uq_trip_table_trip_id'), 'trip_table', ['trip_id'])
    op.create_unique_constraint(op.f('uq_user_table_user_id'), 'user_table', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_table_user_id'), 'user_table', type_='unique')
    op.drop_constraint(op.f('uq_trip_table_trip_id'), 'trip_table', type_='unique')
    op.drop_constraint(op.f('uq_destination_table_destination_id'), 'destination_table', type_='unique')
    op.drop_constraint(op.f('uq_activity_table_activity_id'), 'activity_table', type_='unique')
    # ### end Alembic commands ###
