"""first migration

Revision ID: 77a930bcd672
Revises: 
Create Date: 2025-10-25 19:00:44.303953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a930bcd672'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_table',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('trip_type', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('estimated_budget', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('trip_id', name=op.f('pk_trip_table')),
    sa.UniqueConstraint('trip_id', name=op.f('uq_trip_table_trip_id'))
    )
    op.create_table('user_table',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_picture', sa.String(length=200), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_table')),
    sa.UniqueConstraint('email', name=op.f('uq_user_table_email')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_table_user_id')),
    sa.UniqueConstraint('username', name=op.f('uq_user_table_username'))
    )
    op.create_table('destination_table',
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('best_time_to_visit', sa.String(length=100), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip_table.trip_id'], name=op.f('fk_destination_table_trip_id_trip_table'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('destination_id', name=op.f('pk_destination_table')),
    sa.UniqueConstraint('destination_id', name=op.f('uq_destination_table_destination_id'))
    )
    op.create_table('user_trip_association_course',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip_table.trip_id'], name=op.f('fk_user_trip_association_course_trip_id_trip_table'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], name=op.f('fk_user_trip_association_course_user_id_user_table'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'trip_id', name=op.f('pk_user_trip_association_course'))
    )
    op.create_table('activity_table',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destination_table.destination_id'], name=op.f('fk_activity_table_destination_id_destination_table'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', name=op.f('pk_activity_table')),
    sa.UniqueConstraint('activity_id', name=op.f('uq_activity_table_activity_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_table')
    op.drop_table('user_trip_association_course')
    op.drop_table('destination_table')
    op.drop_table('user_table')
    op.drop_table('trip_table')
    # ### end Alembic commands ###
