"""first migration

Revision ID: 900c42f1c4ea
Revises: 1abf36403bab
Create Date: 2025-10-10 20:28:32.578629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900c42f1c4ea'
down_revision: Union[str, Sequence[str], None] = '1abf36403bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_destination_table_trip_id_trip_table'), 'destination_table', type_='foreignkey')
    op.create_foreign_key(op.f('fk_destination_table_trip_id_trip_table'), 'destination_table', 'trip_table', ['trip_id'], ['trip_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_destination_table_trip_id_trip_table'), 'destination_table', type_='foreignkey')
    op.create_foreign_key(op.f('fk_destination_table_trip_id_trip_table'), 'destination_table', 'trip_table', ['trip_id'], ['trip_id'])
    # ### end Alembic commands ###
